### ISSUE TITLE
Doesn't work with dataloader-37.0.0-uber.jar

### ISSUE THREAD

**Issue by RedaBenh** [sthiyaga/dataloader#1]
Hi ,

Can you please confirm that only supported version of dataloader jar is 30.0.0 ?

```

➜  dataloader git:(master) ✗ bin/process.sh csvAccountExtractProcess
2016-07-02 17:01:03,513 INFO  [main] controller.Controller initLog (Controller.java:389) - Using built-in logging configuration, no log-conf.xml in /XYZ/dataloader/log-conf.xml
2016-07-02 17:01:03,522 INFO  [main] controller.Controller initLog (Controller.java:391) - The log has been initialized
2016-07-02 17:01:03,527 INFO  [main] process.ProcessConfig getBeanFactory (ProcessConfig.java:104) - Loading process configuration from config file: /XYZ/dataloader/conf/process-conf.xml
2016-07-02 17:01:03,653 INFO  [main] support.AbstractApplicationContext prepareRefresh (AbstractApplicationContext.java:495) - Refreshing org.springframework.context.support.FileSystemXmlApplicationContext@3d012ddd: startup date [Sat Jul 02 17:01:03 CEST 2016]; root of context hierarchy
2016-07-02 17:01:03,719 INFO  [main] xml.XmlBeanDefinitionReader loadBeanDefinitions (XmlBeanDefinitionReader.java:315) - Loading XML bean definitions from URL [file:/XYZ/dataloader/conf/process-conf.xml]
2016-07-02 17:01:03,782 INFO  [main] support.DefaultListableBeanFactory preInstantiateSingletons (DefaultListableBeanFactory.java:557) - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@69d9c55: defining beans [csvAccountExtractProcess]; root of factory hierarchy
2016-07-02 17:01:03,833 INFO  [csvAccountExtract] controller.Controller initConfig (Controller.java:327) - config dir created at /XYZ/dataloader/conf
2016-07-02 17:01:04,542 INFO  [csvAccountExtract] controller.Controller initConfig (Controller.java:355) - The controller config has been initialized
2016-07-02 17:01:04,544 INFO  [csvAccountExtract] process.ProcessRunner run (ProcessRunner.java:116) - Initializing process engine
2016-07-02 17:01:04,544 INFO  [csvAccountExtract] process.ProcessRunner run (ProcessRunner.java:119) - Loading parameters
2016-07-02 17:01:04,554 INFO  [csvAccountExtract] process.ProcessRunner run (ProcessRunner.java:127) - Logging in to: https://login.salesforce.com
2016-07-02 17:01:04,559 INFO  [csvAccountExtract] client.PartnerClient login (PartnerClient.java:479) - Beginning Partner Salesforce login ....
2016-07-02 17:01:04,585 INFO  [csvAccountExtract] client.PartnerClient loginInternal (PartnerClient.java:523) - Salesforce login to https://login.salesforce.com/services/Soap/u/37.0 as user easybackup@easyforce.io.entr
2016-07-02 17:01:05,342 INFO  [csvAccountExtract] dao.DataAccessObjectFactory getDaoInstance (DataAccessObjectFactory.java:51) - Instantiating data access object: data/accountExtract.csv of type: csvWrite
2016-07-02 17:01:05,343 INFO  [csvAccountExtract] process.ProcessRunner run (ProcessRunner.java:132) - Checking the data access object connection
2016-07-02 17:01:05,344 INFO  [csvAccountExtract] process.ProcessRunner run (ProcessRunner.java:137) - Setting field types
2016-07-02 17:01:05,735 INFO  [csvAccountExtract] process.ProcessRunner run (ProcessRunner.java:141) - Setting object reference types
2016-07-02 17:01:06,773 INFO  [csvAccountExtract] process.ProcessRunner run (ProcessRunner.java:145) - Creating Map
2016-07-02 17:01:06,777 FATAL [main] process.ProcessRunner topLevelError (ProcessRunner.java:238) - Unable to run process csvAccountExtract
java.lang.RuntimeException: com.salesforce.dataloader.mapping.Mapper$InvalidMappingException: No such field recordtypeid on entity Account
  at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:162)
  at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:100)
  at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:253)
Caused by: com.salesforce.dataloader.mapping.Mapper$InvalidMappingException: No such field recordtypeid on entity Account
  at com.salesforce.dataloader.mapping.SOQLMapper.getSfdcField(SOQLMapper.java:219)
  at com.salesforce.dataloader.mapping.SOQLMapper.evalSfdcField(SOQLMapper.java:210)
  at com.salesforce.dataloader.mapping.SOQLMapper.evalSfdcField(SOQLMapper.java:186)
  at com.salesforce.dataloader.mapping.SOQLMapper.normalizeSoql(SOQLMapper.java:170)
  at com.salesforce.dataloader.mapping.SOQLMapper.addSoqlFieldMapping(SOQLMapper.java:166)
  at com.salesforce.dataloader.mapping.SOQLMapper.putPropertyEntry(SOQLMapper.java:99)
  at com.salesforce.dataloader.mapping.Mapper.putPropertyFileMappings(Mapper.java:147)
  at com.salesforce.dataloader.mapping.Mapper.putPropertyFileMappings(Mapper.java:142)
  at com.salesforce.dataloader.mapping.Mapper.<init>(Mapper.java:89)
  at com.salesforce.dataloader.mapping.SOQLMapper.<init>(SOQLMapper.java:58)
  at com.salesforce.dataloader.controller.Controller.createMapper(Controller.java:194)
  at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:146)
  ... 2 more
➜  dataloader git:(master) ✗ 

```

**Comment by RedaBenh** [comment]
Sorry i did'nt read the complete error message.
`No such field recordtypeid on entity Account`
I remove recordtypeid because i didn't have a recordtype in my org.

It works fine with the last version of dataloader-37.0.0-uber.jar :)

Thanks
Reda
